#!/usr/bin/env python3
"""Publish a CSV content calendar to Google Sheets with gogcli."""
from __future__ import annotations

import argparse
import csv
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, List


def run(cmd: List[str]) -> Dict[str, Any]:
    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if proc.returncode != 0:
        raise RuntimeError(f"Command failed ({proc.returncode}): {' '.join(cmd)}\n{proc.stderr.strip()}")
    return json.loads(proc.stdout)


def read_calendar(path: Path) -> List[List[str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        return [row for row in reader]


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a Google Sheet from an Attract Signal calendar CSV.")
    parser.add_argument("--calendar", required=True, type=Path, help="CSV calendar generated by generate_report.py")
    parser.add_argument("--title", required=True, help="Spreadsheet title")
    parser.add_argument("--parent", default=None, help="Optional Drive folder ID")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if shutil.which("gog") is None:
        print("ERROR: gogcli is required. Install with: brew install openclaw/tap/gogcli", file=sys.stderr)
        return 2
    if not args.calendar.exists():
        print(f"ERROR: calendar file not found: {args.calendar}", file=sys.stderr)
        return 2
    rows = read_calendar(args.calendar)
    create_cmd = ["gog", "sheets", "create", args.title, "--sheets", "Calendar", "--json"]
    if args.parent:
        create_cmd.extend(["--parent", args.parent])
    if args.dry_run:
        print(json.dumps({"dry_run": True, "create_command": create_cmd, "rows": len(rows)}, indent=2))
        return 0
    created = run(create_cmd)
    spreadsheet_id = (
        (created.get("spreadsheet") or {}).get("spreadsheetId")
        or (created.get("file") or {}).get("id")
        or created.get("spreadsheetId")
        or created.get("id")
    )
    if not spreadsheet_id:
        print(json.dumps(created, indent=2))
        raise RuntimeError("Google Sheet was created but no spreadsheet ID was returned")
    run([
        "gog",
        "sheets",
        "update",
        spreadsheet_id,
        "Calendar!A1",
        "--values-json",
        json.dumps(rows),
        "--json",
    ])
    print(json.dumps({"created": created, "spreadsheet_id": spreadsheet_id, "rows_written": len(rows)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
